version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -p 3001 -b 0.0.0.0
    volumes:
      - .:/app
    ports: 
      - "3001:3001"
    environment:
      RAILS_ENV: production
      RAILS_SECRET_KEY_BASE: ${RAILS_SECRET_KEY_BASE}
      DATABASE_HOST: ${PROD_DATABASE_HOST}   
      DATABASE_USERNAME: ${PROD_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${PROD_DATABASE_PASSWORD}
      DATABASE_NAME: ${PROD_DATABASE_NAME}
